### ISSUE TITLE
docker socket address hardcoded in main.rs

### ISSUE THREAD

**Issue by solarsail** [vv9k/dockeye#22]
It seems that the default address is always used despite what is set in the configuration file.

https://github.com/vv9k/dockeye/blob/master/src/main.rs#L15
```rust
DockerWorker::spawn(rt, DEFAULT_DOCKER_ADDR.to_string(), rx_req, tx_rsp);
```

**Comment by vv9k** [comment]
Should be resolved now :) Thanks for the report!
