### ISSUE TITLE
Make font sizes configurable

### ISSUE THREAD

**Issue by fergalmoran** [vv9k/dockeye#30]
Possibly a matter of personal taste but for me the fonts are a bit small in HiDPI - it would be great to get a config option to choose the font style and size.

My config is
![image](https://user-images.githubusercontent.com/309139/143952793-ef17f378-ecfd-4708-b5ce-1c969f6af336.png)

and the UI looks like this, which to me is a bit smaller than I would like. 
![image](https://user-images.githubusercontent.com/309139/143953515-7e6d033e-49bc-49e5-bf0f-5018d4236818.png)

**Comment by vv9k** [comment]
Thanks for the report! I do agree that an option to customize the font size should be available in settings. Will work on this soon :)

**Comment by vv9k** [comment]
Should be implemented :) Thanks again for the feedback!
