### ISSUE TITLE
client version 1.41 is too new. 

### ISSUE THREAD

**Issue by rikosintie** [vv9k/dockeye#36]
Hello, Thanks for creating this project! 

I downloaded the dockeye-0.1.0-x86_64-unknown-linux-tar-gz file and extracted it. 

It started up without issue but in the terminal window I get the following:

dockeye                                                        [22:07:42]
 ERROR dockeye::worker > failed to list containers: error 400 Bad Request - client version 1.41 is too new. Maximum supported API version is 1.40
 
 The OS is Ubuntu 20:04, shell is zsh 5.8 (x86_64-ubuntu-linux-gnu)

I don't know how to troubleshoot this. Can you point me in the right direction?

Thanks!

**Comment by vv9k** [comment]
Hello, thank you for the report!

Could you try running from the terminal with `RUST_LOG=dockeye=trace,docker_api=trace dockeye` and submitting the logs here?

**Comment by vv9k** [comment]
Ok, I think the problem is that the docker client library used here always uses the latest version - 1.41 that is unavailable on your machine. I'll have to make the necessary changes to the library first but it should be resolved soon :)

**Comment by vv9k** [comment]
I pushed some changes in 3c4b9f0 that should resolve the problem. You could try building the master branch to see if the issue still persists, otherwise we'll have to wait for the next release to hit with the prebuilt package.

**Comment by rikosintie** [comment]
Thanks, vv9k; 
I will wait for the release version, I found out that I'm a consumer, not a developer when I tried to build it! :-)

**Comment by vv9k** [comment]
The release is out, let me know if it works! :)

**Comment by rikosintie** [comment]
Hello, vv9k,
Sorry for the long delay. I looked at [Install Docker on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) and realized that my Docker was quite old.

I followed the instructions, upgraded, then grabbed the new version of Dockeye and it works great. 

Thanks for helping me out and creating this project.  I am now learning its features.
