### ISSUE TITLE
What the diff between dockeye and portainer

### ISSUE THREAD

**Issue by shaygover** [vv9k/dockeye#55]
Just wondering what this project motivation is.

**Comment by vv9k** [comment]
Hello! Thanks for your interest in dockeye. The main difference Is that dockeye is not a web application that you open in your browser but rather a native desktop application. And this is enough of a reason for me to create dockeye :) I'm just not a fan of having everything in my browser that's all.

**Comment by shaygover** [comment]
That's an excellent motivation
